/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hjsilnxsitpbjehrlnbj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqc2lsbnhzaXRwYmplaHJsbmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyOTY2OTUsImV4cCI6MjA4MDg3MjY5NX0.ZQwNbGlTdKwXcTBrytlEJYdDiAX224m---SEOWPuRJI"